apiVersion: v1
kind: Secret
metadata:
  name: falco-telegram-secret
  namespace: falco
type: Opaque
stringData:
  TELEGRAM_TOKEN: "DIEN_BOT_TOKEN_THAT_VAO_DAY"
  TELEGRAM_CHATID: "DIEN_CHAT_ID_THAT_VAO_DAY"